/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.projectmanager.frms;

import com.projectmanager.models.Requisitos;
import com.projectmanager.mysql.MySqlRequisitos;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author root
 */
public class FrmGerRequisitos extends javax.swing.JFrame {

  
       
    public FrmGerRequisitos() {
        
        initComponents();
                        
                
        lblNomeProj.setText(FrmMenuPrincipal.nomeProjeto);
        
        lblAutorProj.setText(FrmMenuPrincipal.nomeComplUser);
               
        txtNomeReq.setText(FrmGerProjeto.requisito.getNomeReq());
        txtModulo.setText(FrmGerProjeto.requisito.getModulo());
        txtFuncionalidades.setText(FrmGerProjeto.requisito.getFuncionalidades());
        txtDtCriacao.setText(FrmGerProjeto.requisito.getDtCriacao());
        txtDtUltMod.setText(FrmGerProjeto.requisito.getDtUltAlteracao());
        lblAutorUltMod.setText(FrmMenuPrincipal.nomeComplUser);
        txtVersao.setText(FrmGerProjeto.requisito.getVersao());
        cmbPrioridade.setSelectedItem(FrmGerProjeto.requisito.getPrioridade());
        cmbComplex.setSelectedItem(FrmGerProjeto.requisito.getComplexidade());
        txtTmpEsfEstimado.setText(Integer.toString(FrmGerProjeto.requisito.getTmpEsforcoEstimado()));
        cmbEstado.setSelectedItem(FrmGerProjeto.requisito.getEstado());
        cmbFase.setSelectedItem(FrmGerProjeto.requisito.getFase());
        txtDescricao.setText(FrmGerProjeto.requisito.getDescricao());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbPrioridade = new javax.swing.JComboBox<>();
        lblNomeProj = new javax.swing.JLabel();
        txtFuncionalidades = new javax.swing.JTextField();
        lblAutorProj = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();
        cmbFase = new javax.swing.JComboBox<>();
        lblVersao = new javax.swing.JLabel();
        txtVersao = new javax.swing.JTextField();
        lblPrioridade = new javax.swing.JLabel();
        lblComplex = new javax.swing.JLabel();
        lblTmpEsfEstimado = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblFase = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtTmpEsfEstimado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        btnAtualizar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        lblDescrFrame = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        lblModulo = new javax.swing.JLabel();
        cmbComplex = new javax.swing.JComboBox<>();
        txtNomeReq = new javax.swing.JTextField();
        cmbEstado = new javax.swing.JComboBox<>();
        txtModulo = new javax.swing.JTextField();
        lblFunc = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDtCriacao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDtUltMod = new javax.swing.JTextField();
        lblAutorUltMod = new javax.swing.JLabel();
        lblAutor1 = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbPrioridade.setEditable(true);
        cmbPrioridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baixa", "Média", "Alta", "Urgente" }));

        lblNomeProj.setText("...");

        lblAutorProj.setText("...");

        lblAutor.setText("Autor:");

        cmbFase.setEditable(true);
        cmbFase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblVersao.setText("Versão:");

        lblPrioridade.setText("Prioridade:");

        lblComplex.setText("Complexidade:");

        lblTmpEsfEstimado.setText("Esforço estimado (h):");

        lblEstado.setText("Estado:");

        lblFase.setText("Fase:");

        lblDescricao.setText("Descrição:");

        lblId.setText("Nome do projeto:");

        txtTmpEsfEstimado.setToolTipText("");

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane1.setViewportView(txtDescricao);

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        lblDescrFrame.setText("Gerenciamento de Requisito");

        btnFechar.setText("Voltar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        lblNome.setText("Nome do requisito:");

        lblModulo.setText("Módulo:");

        cmbComplex.setEditable(true);
        cmbComplex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baixa", "Media", "Alta" }));

        cmbEstado.setEditable(true);
        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inicial", "Intermediario", "Final", "Concluído" }));

        lblFunc.setText("Funcionalidades:");

        jLabel1.setText("Data de criação:");

        txtDtCriacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDtCriacaoActionPerformed(evt);
            }
        });

        jLabel2.setText("Data de modificação:");

        txtDtUltMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDtUltModActionPerformed(evt);
            }
        });

        lblAutorUltMod.setText("...");

        lblAutor1.setText("Autor da última modiificação:");

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(lblDescrFrame)
                .addContainerGap(135, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeReq, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNomeProj, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblModulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFunc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFuncionalidades, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDtCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAutorProj, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAutor1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAutorUltMod, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDtUltMod, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblVersao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVersao, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPrioridade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbPrioridade, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblComplex)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbComplex, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTmpEsfEstimado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTmpEsfEstimado, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbFase, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnAtualizar)
                            .addGap(18, 18, 18)
                            .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExcluir)
                            .addGap(18, 18, 18)
                            .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblDescricao)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblDescrFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(lblNomeProj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNomeReq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModulo)
                    .addComponent(txtModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFunc)
                    .addComponent(txtFuncionalidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDtCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutor)
                    .addComponent(lblAutorProj, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDtUltMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutor1)
                    .addComponent(lblAutorUltMod, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVersao)
                    .addComponent(txtVersao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrioridade)
                    .addComponent(cmbPrioridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComplex)
                    .addComponent(cmbComplex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTmpEsfEstimado)
                    .addComponent(txtTmpEsfEstimado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFase)
                    .addComponent(cmbFase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescricao)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFechar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAtualizar)
                        .addComponent(btnLimpar)
                        .addComponent(btnExcluir)))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed

        Date dataAtual = new Date();
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String dataUltAlteracao = dateFormat.format(dataAtual);
        
        System.out.println("Date em String formatada: " + dataUltAlteracao);
        
        Requisitos requisito;

        requisito = new Requisitos(
            FrmGerProjeto.requisito.getIdReq(),                     // 01
            (txtNomeReq.getText()).toUpperCase(),                   // 02
            FrmMenuPrincipal.idProjeto,                             // 03
            (txtModulo.getText()).toUpperCase(),                    // 04
            (txtFuncionalidades.getText()).toUpperCase(),           // 05
            txtDtCriacao.getText(),                                 // 06
            FrmLogin.IdUser,                                        // 07
            dataUltAlteracao,                                       // 08
            FrmLogin.IdUser,                                        // 09
            (txtVersao.getText()).toUpperCase(),                    // 10
            ((String)cmbPrioridade.getSelectedItem()).toUpperCase(),// 11
            ((String)cmbComplex.getSelectedItem()).toUpperCase(),   // 12
            Integer.parseInt(txtTmpEsfEstimado.getText()),          // 13
            ((String)cmbEstado.getSelectedItem()).toUpperCase(),    // 14
            ((String)cmbFase.getSelectedItem()).toUpperCase(),      // 15
            (txtDescricao.getText()));                              // 16
        
        try {
        
            MySqlRequisitos.atualizarRequisito(requisito);
            
            FrmGerProjeto.listaRequisitos = MySqlRequisitos.requisitosByIdUserAndIdProj(FrmLogin.IdUser,FrmMenuPrincipal.idProjeto);
        
        } 
        
        catch (SQLException ex) {
            
            Logger.getLogger(FrmGerRequisitos.class.getName()).log(Level.SEVERE, null, ex);
        
        }       
        
        FrmMenuPrincipal.gerProj.setVisible(true);

        super.dispose();

    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed

        txtNomeReq.setText(null);
        txtModulo.setText(null);
        txtFuncionalidades.setText(null);
        txtDtCriacao.setText(null);
        txtDtUltMod.setText(null);
        txtVersao.setText(null);
        cmbPrioridade.setSelectedIndex(0);
        cmbComplex.setSelectedIndex(0);
        txtTmpEsfEstimado.setText(null);
        cmbEstado.setSelectedIndex(0);
        cmbFase.setSelectedIndex(0);
        txtDescricao.setText(null);           

    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed

        try {
            
            FrmMenuPrincipal.gerProj = new FrmGerProjeto();
            
        } 
        catch (SQLException ex) {
            Logger.getLogger(FrmCadRequisitos.class.getName()).log(Level.SEVERE, null, ex);
        }        
        
        FrmMenuPrincipal.gerProj.setVisible(true);

        super.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void txtDtCriacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDtCriacaoActionPerformed
     
    }//GEN-LAST:event_txtDtCriacaoActionPerformed

    private void txtDtUltModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDtUltModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDtUltModActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
             
        try {
            
            MySqlRequisitos.excluirRequisito(FrmGerProjeto.requisito.getIdReq());
            
            FrmMenuPrincipal.gerProj = new FrmGerProjeto();
                  
        } 
        
        catch (SQLException ex) {
            Logger.getLogger(FrmGerRequisitos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        FrmMenuPrincipal.gerProj.setVisible(true);
        
        super.dispose();
         
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGerRequisitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGerRequisitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGerRequisitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGerRequisitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmGerRequisitos().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> cmbComplex;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbFase;
    private javax.swing.JComboBox<String> cmbPrioridade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblAutor1;
    private javax.swing.JLabel lblAutorProj;
    private javax.swing.JLabel lblAutorUltMod;
    private javax.swing.JLabel lblComplex;
    private javax.swing.JLabel lblDescrFrame;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFase;
    private javax.swing.JLabel lblFunc;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblModulo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeProj;
    private javax.swing.JLabel lblPrioridade;
    private javax.swing.JLabel lblTmpEsfEstimado;
    private javax.swing.JLabel lblVersao;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtDtCriacao;
    private javax.swing.JTextField txtDtUltMod;
    private javax.swing.JTextField txtFuncionalidades;
    private javax.swing.JTextField txtModulo;
    private javax.swing.JTextField txtNomeReq;
    private javax.swing.JTextField txtTmpEsfEstimado;
    private javax.swing.JTextField txtVersao;
    // End of variables declaration//GEN-END:variables
    
}
